apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulse-ingress
  namespace: {{ include "pulse.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "pulse.fullname" . }}
            port:
              number: 80