replicaCount: 1

image:
  repository: flowacr.azurecr.io/pulseapp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  selector: pulse-api

# Environment Variable Mapping
env:
  secretName: pulse-api-secrets
  secretKey: connectionstring

# Volume Configuration
volume:
  mountPath: "/mnt/secrets-store"
  secretProviderClass: pulse-api

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

azure:
  keyvaultName: "devpulseflowkv"
  tenantId: "683a59cf-e313-44e3-95cb-83c3edfdd251"
  identityClientId: "2dc089cd-e64d-44c3-8670-d7a60892c740"
