replicaCount: 2

image:
  repository: prodflowacr.azurecr.io/pulseapp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  selector: pulse-api

# Environment Variable Mapping
env:
  secretName: pulse-api-secrets
  secretKey: connectionstring

# Volume Configuration
volume:
  mountPath: "/mnt/secrets-store"
  secretProviderClass: pulse-api

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

azure:
  keyvaultName: "prodpulseflowkv"
  tenantId: "683a59cf-e313-44e3-95cb-83c3edfdd251"
  identityClientId: "87394d87-e071-48a5-b333-9a8eb80b560f"
