trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pulse-app/**

variables:
  dockerRegistryServiceConnectionDev: 'acr-connect-dev' 
  dockerRegistryServiceConnectionProd: 'acr-connect-prod'    
  
  imageRepository: 'pulseapp' 
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build_Dev
  displayName: "DEV: Build and Push Image"
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: "Build & Push ACR"
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnectionDev)
        tags: |
          $(tag)
          latest
- stage: Build_Prod
  displayName: "Prod: Build and Push Image"
  dependsOn: Build_Dev
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: "Build & Push ACR"
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnectionProd)
        tags: |
          $(tag)
          latest
